# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    postgresql = {
      source  = "cyrilgdn/postgresql"
      version = "1.25.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "3.5.1"
    }
    scaleway = {
      source  = "scaleway/scaleway"
      version = "2.51.0"
    }
    sops = {
      source  = "lokkersp/sops"
      version = "0.6.10"
    }
  }
}
