# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket = "scienta-cloud-state-a86097d6-29e1-11f1-a8c1-d45d64079ca5"
    endpoints = {
      s3 = "https://s3.fr-par.scw.cloud"
    }
    key                         = "apps/repeater-atlas/scaleway/terraform.tfstate"
    region                      = "fr-par"
    skip_credentials_validation = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
  }
}
